name: UpdateAWSProvider
on: push

jobs:
  update-aws-provider:
    name: Update aws provider
    runs-on: ubuntu-latest
    steps:
      - name: create branch develop/update-aws-provider
        run: git checkout -b develop/update-aws-provider master
        