name: UpdateAWSProvider
on: push

jobs:
  update-aws-provider:
    name: Update aws provider
    runs-on: ubuntu-latest
    env:
      TFUPDATE_VERSION: '0.6.1'
      BRANCH_NAME: 'develop/update-aws-provider'
    steps:
      - name: checkout main
        uses: actions/checkout@v2
        with:
          ref: main

      - name: create branch
        run: git checkout -b ${BRANCH_NAME} main

      - name: install tfupdate
        run: |
          wget -P /tmp https://github.com/minamijoyo/tfupdate/releases/download/v${TFUPDATE_VERSION}/tfupdate_${TFUPDATE_VERSION}_linux_amd64.tar.gz
          tar xvf /tmp/tfupdate_${TFUPDATE_VERSION}_linux_amd64.tar.gz -C /tmp
          sudo mv /tmp/tfupdate /usr/local/bin
          sudo chmod +x /usr/local/bin/tfupdate
          tfupdate --version
      
      - name: set LATEST_PROVIDER_VERSION
        run: |
          LATEST_PROVIDER_VERSION=`tfupdate release latest -s tfregistryProvider hashicorp/aws`
          echo "LATEST_PROVIDER_VERSION=${LATEST_PROVIDER_VERSION}" >> $GITHUB_ENV
        
      - name: update aws provider version
        run: tfupdate provider aws -r .

      - name: git add & commit & push
        run: |
          git config --global user.email "42330850+pyawfunc@users.noreply.github.com"
          git config --global user.name "pyawfunc"
          git add .
          git commit -m "Update aws provider to ${LATEST_PROVIDER_VERSION}"
          git push --set-upstream origin ${BRANCH_NAME}
      
      - name: create pull request
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: "main"
          source_branch: "develop/update-aws-provider"
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pr_title: Update aws provider to ${LATEST_PROVIDER_VERSION}
          pr_body: |
            ## 優先度
            プルリクエストの優先度を一つ選択してください。

            - [] 高
              - 急を要する場合に選択してください。
            - [x] 中
              - 業務に必要な作業の場合に選択してください。
            - [] 低
              - 高でも中でもない場合に選択してください。

            ## 前提
            aws providerをバージョンアップします。
            
            ## 概要
            aws providerのバージョンを${LATEST_PROVIDER_VERSION}に上げます。

